#!/usr/bin/env ruby

def sandrorey
  system "clear"
  puts ",,,,,,,,,,,,,,,,,,,,,,,,,8D8DD8DOZ$$O78D8$IZZO8M,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"
  puts ",,,,,,,,,,,,,,,,,,,,,,,,.8O8$Z$I::~:=~:=8ZN$ZI78M,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"
  puts ",,,,,,,,,,,,,,,,,,,,,,,,8$8I?=~~~:::::::~DNO$$777$,,,,,,,,,,,,,,,BENDICIONES,,,,,,,,,"
  puts ",,,,,,,,,,,,,,,,,,,,,,,=788?+=~~::::,,,:==88ZDO8D7,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"
  puts ",,,,,,,,,,,,,,,,,,,,,,,78DD?+=:~:~::::,:~:ONOZ$Z88?,,,,,,,,,,,,,,,,,,,,Y,,,,,,,,,,,,,"
  puts ",,,,,,,,,,,,,,,,,,,,,,.DZON??+=~:::,:,:::~+NDO8N888,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"
  puts ",,,,,,,,,,,,,,,,,,,,,,:+D8$D?=~:,~::~+:::~~DDD8$ODD$,,,,,,,,,,,,BUENAS,NOCHES,,,,,,,,"
  puts ",,,,,,,,,,,,.,,,,,,,,,=Z8DDD??IO?=~=7~Z.=::78DOON$DD,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"
  puts ",,,,,,,,,,,,,,,,,,,,,,~IZNZDIZ~?I?,,=~:~:,~IDDDDNDD88,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"
  puts ",,,,,,,,,,,,,,,,,.,,,.$OD$ODN????~,,,:,,::~I8ZDZ888DDZ,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,"
  puts ",,,,,,,,,,,,,,,,,,.,,?+$ZO88NI++I?,:::~,:~~78ZDDZN8DDOZ,,,,,,,,,,,,,,,,,,,,,,,,.,,,,,"
  puts ",,,,,,,,,,,,,,,,,,,.,=ZO$8DONNII$+~:,~~~,=~78O88DNDDDOO~,,,,,,,,,,,,,,,,,,,,,,,.,,,,,"
  puts ",,,,,,,,,,,,,,,,,,,,,:.OOD8ODN$+7?=+~:~=~~~7DDDDNDDDDZO8O,,,,,,,,,,,,,,,,,,,,,,.,,,,,"
  puts ",,,,,,,,,,,,,,.,,,,,:I,ZZODODDD7$IO$I+~~:~=8OODDNDNMNDDD8DD:,,,,,,,,,,,,,,,,,,,.,,,,,"
  puts ",,,,,,,,,,,,,,,,,,,,,,.ZZODDONND7??=::::=+?Z8D8ODDND8DOZOOZO$OD,,,,,,,,,,,,,,,,,,,,,,"
  puts ",,,,,,,,,,,,,,,,,,,,,=?OZZO8DD8DDD?=~:~===++=DZ8OODDD8D88OOZ$Z$Z$.,,,,,,,,,,,,,,,,,,,"
  puts ",,,,,,,,,,,,,,,,,,.,,,:8$ZOOOZD88DDNO~::~?~+888O888NDD8888$7ZZ88$Z7,,,,,,,,,,,,.,,,,,"
  puts ",,,,,,,,,,,,,,,,,,.,,=+7ZOODD7ZZDND8DOOI+=7OOOZOOODND88OZ$7O8O7+$O=N,,,,,,,,,,,.,,,,,"
  puts ",,,,,,,,,,,,,,,,,,,.,,~O8DOOZZZDDDNDZN~?7$ZOODOO88NND8OO+OD??ZDDZZZ.M.,,,,,,,,,,,,,,,"
  puts ",,,,,,,,,,,,,,,,:,,, .+88OO7D7IO8ZD88DO?ZZ$ZZZOO8DDD8OO8ZD88OOOOZ$$+Z:,,,,,,,,,,,,,,,"
  puts ",,,,,,,,,,,,,,,,,?::,.ZZO88Z8Z8ZDON?MIN7Z$ZZZZZ8ODD88OO8OO$ZZZZZZOO$??,,,,,,,,,,,,,,,"
  puts ",,,,,,,,,,,,.,,,.I?,.:ZZD88D88D8DDZ$+?7Z$$$ZZNO8DD8OZO,=ZO$7$ZZZOZODO,:,.,,,,,,,,,,,,"
  puts ",,,,,,,,,,,,,,,,,?~~~::8DDZO,.OI887Z77$Z$8$ZZO8NDOOZ~:,,OOZO?OZZOZO$7,,,,,,,,,,.,,,,,"
  puts ",,,,,,,,,,,,,,,,.N??~,~D+~:,,,O88Z?D7$Z$$ZZ8O8D88O8+=~8OZI$ZI7ZOOOO$I.~,,,,,,,,,,,,,,"
  puts ",,,,,,,,,,,,,,ZZ$=+=I7==+=,,,8O8ZZ$+$O$$7Z8D8$8O8=,~,.OO7$ZZ?Z8OOOOOZ.~,,,,,,,,,,,,,,"
  puts ",,,,,,,,,,,IZ$ZDI8????I?+?=,8ODOOZD:OO.7OOO8O88~,,,,~O8Z$7$7$8ZZOZ$D$..::,,,,,,,,,,,,"
  puts ",,,,,,,,,,$$$ZOD??O??~?~==OO8OZ8O?DIOO~:,,,7D8~~:::,Z$$$$7Z$+O7OZ$88$=:+,,,,,,,,,,,,,"
  puts ",,,,,,,,,$ZZZ$DD8??7IMZDOOO$Z88DO7DZOOO+=?~:,,,:,::,:~Z$$7$ZZZZ$$ZDZ77:,,,,,,,,,,,,,,"
  puts ""
  puts ""
  puts ""
  puts "Hola buenas noches, tiene usted una abuela que se llama Maria?"
  puts "mmmm no ..."
  puts "No pasa nada, usted no se acuerda."
  puts ""
  puts ""
  sleep 3
  puts "El jugador que marcara 10 goles esta semana és: "
  files = Dir.entries("#{DATA_DIR}")
  player = files.sample
  puts "#{player}"
  puts ""
  puts ""
  sleep 5
end
